//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGSW_VKMSPOCs
    {
        public string TopSection_Section { get; set; }
        public string BU_ID { get; set; }
        public string VKMspoc { get; set; }
        public int ID { get; set; }
        public string TOPSECTION { get; set; }
    }
}
