//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwDamageCost_Table
    {
        public int ID { get; set; }
        public string BU { get; set; }
        public string Location { get; set; }
        public string Month { get; set; }
        public string Item_Name { get; set; }
        public string Qty { get; set; }
        public string Project_Team { get; set; }
        public Nullable<decimal> Cost_inEUR { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public string RequestorNT { get; set; }
        public string Hw_status { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string Year { get; set; }
        public string Remarks { get; set; }
    }
}
