//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromasterImport_HWInfoEntities : DbContext
    {
        public PromasterImport_HWInfoEntities()
            : base("name=PromasterImport_HWInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hardware_Desc_Pr> Hardware_Desc_Pr { get; set; }
        public virtual DbSet<Sites_AS> Sites_AS { get; set; }
    }
}
