//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOTONData_Table_2022
    {
        public int ID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public string NTID { get; set; }
        public string Employee_Group { get; set; }
        public string Employee_SubGroup { get; set; }
        public string Level { get; set; }
        public string DOJ { get; set; }
        public string ContractEndDate { get; set; }
        public string HC { get; set; }
        public string PersonalCapacity { get; set; }
        public string PersonalCapacity_ { get; set; }
        public string PC_Remarks { get; set; }
        public string PC_Remarks_StartDate { get; set; }
        public string PC_Remarks_EndDate { get; set; }
        public string PartTimePercentage { get; set; }
        public string PartTimeEndDate { get; set; }
        public string Role { get; set; }
        public string BU { get; set; }
        public string TopSection { get; set; }
        public string Section { get; set; }
        public string Department { get; set; }
        public string Group { get; set; }
        public string OrgUnit { get; set; }
        public string IsCorparate { get; set; }
        public string BusinessArea { get; set; }
        public string PersonnelArea { get; set; }
        public string PersonnelSubArea { get; set; }
        public string CostCenter { get; set; }
    }
}
