//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelCost_Table
    {
        public int ID { get; set; }
        public string Cmmt_Item { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Budget_Plan { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Bud_Inv { get; set; }
        public Nullable<int> Open { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
