//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetingToolDB_Entities : DbContext
    {
        public BudgetingToolDB_Entities()
            : base("name=BudgetingToolDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C2019_CategorySummary> C2019_CategorySummary { get; set; }
        public virtual DbSet<C2019_CostElementSummary> C2019_CostElementSummary { get; set; }
        public virtual DbSet<BU_SPOCS> BU_SPOCS { get; set; }
        public virtual DbSet<BU_Table> BU_Table { get; set; }
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<CmmtItem_Table> CmmtItem_Table { get; set; }
        public virtual DbSet<Cockpit_UserIDs_Table> Cockpit_UserIDs_Table { get; set; }
        public virtual DbSet<Cockpit_UserIDs_Table_OLD> Cockpit_UserIDs_Table_OLD { get; set; }
        public virtual DbSet<CostElement_Table> CostElement_Table { get; set; }
        public virtual DbSet<Currency_Conversion_Table> Currency_Conversion_Table { get; set; }
        public virtual DbSet<Currency_Table> Currency_Table { get; set; }
        public virtual DbSet<DEPT_OEM_Table> DEPT_OEM_Table { get; set; }
        public virtual DbSet<DEPT_Table> DEPT_Table { get; set; }
        public virtual DbSet<DEPTMapping_Table> DEPTMapping_Table { get; set; }
        public virtual DbSet<Depts_Table_Aug1> Depts_Table_Aug1 { get; set; }
        public virtual DbSet<Fund_Table> Fund_Table { get; set; }
        public virtual DbSet<GroupMapping_Table> GroupMapping_Table { get; set; }
        public virtual DbSet<Groups_Table> Groups_Table { get; set; }
        public virtual DbSet<Groups_Table_Aug> Groups_Table_Aug { get; set; }
        public virtual DbSet<Groups_Table_New> Groups_Table_New { get; set; }
        public virtual DbSet<Groups_Table_Test> Groups_Table_Test { get; set; }
        public virtual DbSet<HC_Budget_Table> HC_Budget_Table { get; set; }
        public virtual DbSet<HC_Role_Table> HC_Role_Table { get; set; }
        public virtual DbSet<HC_Role_Table_mergedRemarkRolewiserole> HC_Role_Table_mergedRemarkRolewiserole { get; set; }
        public virtual DbSet<HC_SkillSet_Table_onlySkillnotmergedVKMRoleRemarks> HC_SkillSet_Table_onlySkillnotmergedVKMRoleRemarks { get; set; }
        public virtual DbSet<HC_Table> HC_Table { get; set; }
        public virtual DbSet<HwDamageCost_Location_Table> HwDamageCost_Location_Table { get; set; }
        public virtual DbSet<HwDamageCost_Month_Table> HwDamageCost_Month_Table { get; set; }
        public virtual DbSet<HWDamageCost_OEM_Table> HWDamageCost_OEM_Table { get; set; }
        public virtual DbSet<HwDamageCost_Table> HwDamageCost_Table { get; set; }
        public virtual DbSet<HwDamageCost_UserIDs_Table> HwDamageCost_UserIDs_Table { get; set; }
        public virtual DbSet<Internal_UserIDs_Table> Internal_UserIDs_Table { get; set; }
        public virtual DbSet<ItemsCostList_Table> ItemsCostList_Table { get; set; }
        public virtual DbSet<ItemsCostList_Table_bkp_2021> ItemsCostList_Table_bkp_2021 { get; set; }
        public virtual DbSet<ItemsCostList_Table_new> ItemsCostList_Table_new { get; set; }
        public virtual DbSet<ItemsCostList_Table_wrong> ItemsCostList_Table_wrong { get; set; }
        public virtual DbSet<LeadTime_Table> LeadTime_Table { get; set; }
        public virtual DbSet<OEM_Table> OEM_Table { get; set; }
        public virtual DbSet<Order_Status_Table> Order_Status_Table { get; set; }
        public virtual DbSet<Order_Table_orderview_test> Order_Table_orderview_test { get; set; }
        public virtual DbSet<OrderingRequestor_Table> OrderingRequestor_Table { get; set; }
        public virtual DbSet<Planning_EM_Table> Planning_EM_Table { get; set; }
        public virtual DbSet<Planning_EM_Table_keyissue> Planning_EM_Table_keyissue { get; set; }
        public virtual DbSet<Planning_HOE_Table> Planning_HOE_Table { get; set; }
        public virtual DbSet<PlanningRequestor_Table> PlanningRequestor_Table { get; set; }
        public virtual DbSet<PODet_Temp> PODet_Temp { get; set; }
        public virtual DbSet<PODetails_Table> PODetails_Table { get; set; }
        public virtual DbSet<PODetails_Table_old> PODetails_Table_old { get; set; }
        public virtual DbSet<ReqTable_MayRFODemo> ReqTable_MayRFODemo { get; set; }
        public virtual DbSet<RequestItems_Table> RequestItems_Table { get; set; }
        public virtual DbSet<RequestItems_Table_23Aug_allBUs_ItemDetailsUpdationBKP> RequestItems_Table_23Aug_allBUs_ItemDetailsUpdationBKP { get; set; }
        public virtual DbSet<RequestItems_Table_24aug_check> RequestItems_Table_24aug_check { get; set; }
        public virtual DbSet<RequestItems_Table_24augNOTcrt> RequestItems_Table_24augNOTcrt { get; set; }
        public virtual DbSet<RequestItems_Table_AprBonaparteUpdate> RequestItems_Table_AprBonaparteUpdate { get; set; }
        public virtual DbSet<RequestItems_Table_beforefinal24aug> RequestItems_Table_beforefinal24aug { get; set; }
        public virtual DbSet<RequestItems_Table_bkp> RequestItems_Table_bkp { get; set; }
        public virtual DbSet<RequestItems_Table_bkp_2020_plan> RequestItems_Table_bkp_2020_plan { get; set; }
        public virtual DbSet<RequestItems_Table_bkp_apr2022> RequestItems_Table_bkp_apr2022 { get; set; }
        public virtual DbSet<RequestItems_Table_Dec21> RequestItems_Table_Dec21 { get; set; }
        public virtual DbSet<RequestItems_Table_orderview_test_test> RequestItems_Table_orderview_test_test { get; set; }
        public virtual DbSet<RequestItems_Table_orderview_test1_11> RequestItems_Table_orderview_test1_11 { get; set; }
        public virtual DbSet<RequestItems_Table_withEntriesforOrderPh> RequestItems_Table_withEntriesforOrderPh { get; set; }
        public virtual DbSet<RequestItems_Table2022> RequestItems_Table2022 { get; set; }
        public virtual DbSet<RequestItemsList_2019> RequestItemsList_2019 { get; set; }
        public virtual DbSet<Section_Table> Section_Table { get; set; }
        public virtual DbSet<SPOTONData_bkp2021> SPOTONData_bkp2021 { get; set; }
        public virtual DbSet<SPOTONData_Table_2021> SPOTONData_Table_2021 { get; set; }
        public virtual DbSet<SPOTONData_Table_2021_Augbkp> SPOTONData_Table_2021_Augbkp { get; set; }
        public virtual DbSet<SPOTONData_Table_2021_Junebkp> SPOTONData_Table_2021_Junebkp { get; set; }
        public virtual DbSet<SPOTONData_Table_2022> SPOTONData_Table_2022 { get; set; }
        public virtual DbSet<SPOTONData_Table_2022_BKP> SPOTONData_Table_2022_BKP { get; set; }
        public virtual DbSet<SPOTONData_Table_Latest> SPOTONData_Table_Latest { get; set; }
        public virtual DbSet<tbl_ItemsCostList> tbl_ItemsCostList { get; set; }
        public virtual DbSet<tbl_RequestItemsRepo> tbl_RequestItemsRepo { get; set; }
        public virtual DbSet<tbl_UserIDs> tbl_UserIDs { get; set; }
        public virtual DbSet<tbl_UserIDs_Table> tbl_UserIDs_Table { get; set; }
        public virtual DbSet<TravelCost_Table> TravelCost_Table { get; set; }
        public virtual DbSet<UserAccess> UserAccesses { get; set; }
        public virtual DbSet<Utilization_Table2021> Utilization_Table2021 { get; set; }
        public virtual DbSet<VKMOrderPlan_Table> VKMOrderPlan_Table { get; set; }
        public virtual DbSet<VKMPlanning_GRMEMSupport> VKMPlanning_GRMEMSupport { get; set; }
        public virtual DbSet<VKMSpocHead> VKMSpocHeads { get; set; }
        public virtual DbSet<dept_bkp_2022> dept_bkp_2022 { get; set; }
        public virtual DbSet<DEPT_Table_2022xcBKP> DEPT_Table_2022xcBKP { get; set; }
        public virtual DbSet<Groups_Table_Test_2022xcBKP> Groups_Table_Test_2022xcBKP { get; set; }
        public virtual DbSet<groups_table_test_bkp2022> groups_table_test_bkp2022 { get; set; }
        public virtual DbSet<HC_SkillSet_Table> HC_SkillSet_Table { get; set; }
        public virtual DbSet<ItemsCostList_Table_BeforeConversion2022> ItemsCostList_Table_BeforeConversion2022 { get; set; }
        public virtual DbSet<ItemsCostList_Table_beforeVKM2023> ItemsCostList_Table_beforeVKM2023 { get; set; }
        public virtual DbSet<ItemsCostList_Table_bkp_bfor2023_cicharges> ItemsCostList_Table_bkp_bfor2023_cicharges { get; set; }
        public virtual DbSet<ItemsCostList_Table_LATESTBKP> ItemsCostList_Table_LATESTBKP { get; set; }
        public virtual DbSet<ItemsCostList_Table_old> ItemsCostList_Table_old { get; set; }
        public virtual DbSet<ItemsCostList_Table_test> ItemsCostList_Table_test { get; set; }
        public virtual DbSet<ModeHWInventory> ModeHWInventories { get; set; }
        public virtual DbSet<OEMList> OEMLists { get; set; }
        public virtual DbSet<Planning_EM_table_bkp> Planning_EM_table_bkp { get; set; }
        public virtual DbSet<planning_hoe_table_2022bkp> planning_hoe_table_2022bkp { get; set; }
        public virtual DbSet<PODet_Temp_Table_11> PODet_Temp_Table_11 { get; set; }
        public virtual DbSet<podetails_29apr> podetails_29apr { get; set; }
        public virtual DbSet<podetails_table_AprBonaparteUpdate> podetails_table_AprBonaparteUpdate { get; set; }
        public virtual DbSet<PODetails_Table_bkp_apr2022> PODetails_Table_bkp_apr2022 { get; set; }
        public virtual DbSet<podetails_table_chetan_20may> podetails_table_chetan_20may { get; set; }
        public virtual DbSet<PODetails_Table_Chetan3> PODetails_Table_Chetan3 { get; set; }
        public virtual DbSet<podetails_table_harishchanges> podetails_table_harishchanges { get; set; }
        public virtual DbSet<podetails_table_june27> podetails_table_june27 { get; set; }
        public virtual DbSet<podetails_table_june28> podetails_table_june28 { get; set; }
        public virtual DbSet<PODetails_Table_LATEST_AUG1_22> PODetails_Table_LATEST_AUG1_22 { get; set; }
        public virtual DbSet<Req> Reqs { get; set; }
        public virtual DbSet<req_table_29apr> req_table_29apr { get; set; }
        public virtual DbSet<RequestItems_Table_beforeProjected_july262022> RequestItems_Table_beforeProjected_july262022 { get; set; }
        public virtual DbSet<RequestItems_Table_bforeChetanUpload> RequestItems_Table_bforeChetanUpload { get; set; }
        public virtual DbSet<RequestItems_Table_bforeChetanUpload1> RequestItems_Table_bforeChetanUpload1 { get; set; }
        public virtual DbSet<RequestItems_Table_BKP_27MAY> RequestItems_Table_BKP_27MAY { get; set; }
        public virtual DbSet<RequestItems_Table_bkp12Dec2021_beforegivingEditAccess_to_Kavi_to_fillVKM2021PO> RequestItems_Table_bkp12Dec2021_beforegivingEditAccess_to_Kavi_to_fillVKM2021PO { get; set; }
        public virtual DbSet<requestitems_table_bkpjune2022_latest> requestitems_table_bkpjune2022_latest { get; set; }
        public virtual DbSet<requestitems_table_chetan_20may> requestitems_table_chetan_20may { get; set; }
        public virtual DbSet<RequestItems_Table_Chetan3> RequestItems_Table_Chetan3 { get; set; }
        public virtual DbSet<requestitems_table_july2022> requestitems_table_july2022 { get; set; }
        public virtual DbSet<requestitems_table_june27> requestitems_table_june27 { get; set; }
        public virtual DbSet<requestitems_table_june28> requestitems_table_june28 { get; set; }
        public virtual DbSet<RequestItems_Table_LATEST_AUG1_22> RequestItems_Table_LATEST_AUG1_22 { get; set; }
        public virtual DbSet<RequestItems_Table_LATEST28july22_afterProjected_withNEGATIVEvalues> RequestItems_Table_LATEST28july22_afterProjected_withNEGATIVEvalues { get; set; }
        public virtual DbSet<RequestItems_Table_LATEST28july22_beforeProjected> RequestItems_Table_LATEST28july22_beforeProjected { get; set; }
        public virtual DbSet<RequestItems_Table_misingOrderDts_forall_2021> RequestItems_Table_misingOrderDts_forall_2021 { get; set; }
        public virtual DbSet<RequestItems_Table_orderview_test> RequestItems_Table_orderview_test { get; set; }
        public virtual DbSet<RequestItems_Table_orderview_test1> RequestItems_Table_orderview_test1 { get; set; }
        public virtual DbSet<RequestItems_Table_Sep2022> RequestItems_Table_Sep2022 { get; set; }
        public virtual DbSet<RequestItems_Table_TEMP> RequestItems_Table_TEMP { get; set; }
        public virtual DbSet<RequestItems_Table_TEST> RequestItems_Table_TEST { get; set; }
        public virtual DbSet<SampleUser_Table> SampleUser_Table { get; set; }
        public virtual DbSet<SPOTONData> SPOTONDatas { get; set; }
        public virtual DbSet<SPOTONData_Table_2022_beforeXCReorg_july19> SPOTONData_Table_2022_beforeXCReorg_july19 { get; set; }
        public virtual DbSet<tbl_categoryList> tbl_categoryList { get; set; }
        public virtual DbSet<tbl_depts> tbl_depts { get; set; }
        public virtual DbSet<HWInventory_Table> HWInventory_Table { get; set; }
    }
}
