//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsCostList_Table
    {
        public int S_No { get; set; }
        public string Item_Name { get; set; }
        public string Category { get; set; }
        public string Cost_Element { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public string Currency { get; set; }
        public string Comments { get; set; }
        public string RequestorNT { get; set; }
        public Nullable<double> UnitPriceUSD { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string VendorCategory { get; set; }
        public Nullable<int> BU { get; set; }
        public string Actual_Available_Quantity { get; set; }
        public Nullable<double> Repairable_Cost { get; set; }
        public string Repair_Currency { get; set; }
        public Nullable<double> Repairable_Cost_EUR { get; set; }
        public Nullable<System.DateTime> Repair_UpdatedAt { get; set; }
        public string Repair_UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> VKM_Year { get; set; }
        public Nullable<int> BudgetCode { get; set; }
    }
}
