//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTSO_Pr
    {
        public string System_name { get; set; }
        public string Date { get; set; }
        public string Kernel_Component_IPB_TemperatureReceive_OTSO1Available { get; set; }
        public string Kernel_Component_IPB_TemperatureReceive_OTSO2Available { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Project { get; set; }
    }
}
