//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class podetails_table_june28
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> VKMYear { get; set; }
        public string BU { get; set; }
        public string OEM { get; set; }
        public string GROUP { get; set; }
        public string Dept { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Ordered_Quantity { get; set; }
        public string PO_Number { get; set; }
        public string PIF_ID { get; set; }
        public string Fund { get; set; }
        public string Fund_Center { get; set; }
        public string BudgetCode { get; set; }
        public string ItemDescription { get; set; }
        public string PO_Quantity { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Netvalue { get; set; }
        public Nullable<decimal> Netvalue_USD { get; set; }
        public string Currency { get; set; }
        public string Exchange_Rate { get; set; }
        public Nullable<decimal> Amount_in_INR { get; set; }
        public string Purchasing_Org { get; set; }
        public string Plant { get; set; }
        public Nullable<System.DateTime> PO_Created_On { get; set; }
        public string VendorName { get; set; }
        public string Required_Date { get; set; }
        public Nullable<System.DateTime> Tentative_Delivery_Date { get; set; }
        public string CW { get; set; }
        public Nullable<System.DateTime> Actual_Delivery_Date { get; set; }
        public string Difference_in_DeliveRy_Date { get; set; }
        public string Actal_Amt { get; set; }
        public string Negotiated_Amt { get; set; }
        public Nullable<decimal> Savings { get; set; }
        public string Current_status { get; set; }
        public string PO_Remarks { get; set; }
    }
}
