//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public string RbCode { get; set; }
        public string CountryCode { get; set; }
        public string TimeZone { get; set; }
    }
}
