//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOTONData_bkp2021
    {
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public string NTID { get; set; }
        public string Level { get; set; }
        public string Textbox46 { get; set; }
        public string IsCorporate { get; set; }
        public string HeadCount1 { get; set; }
        public string PersonalCapacity { get; set; }
        public string PC_WithHoliday1 { get; set; }
        public string DE__WithHoliday_StartDate { get; set; }
        public string DE__WithHoliday_EndDate { get; set; }
        public string PC_WithHolidayRemarks { get; set; }
        public string ContractEndDate { get; set; }
        public string PartTimeEndDate { get; set; }
        public string PartTimePercentage { get; set; }
        public string Role { get; set; }
        public string BU_Parent { get; set; }
        public string Section { get; set; }
        public string Department { get; set; }
        public string Group { get; set; }
        public string Location { get; set; }
        public string PersonnelArea { get; set; }
        public string WorkPlace { get; set; }
        public string DOJ1 { get; set; }
        public string Textbox34 { get; set; }
        public string Textbox35 { get; set; }
    }
}
