//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKMOrderPlan_Table
    {
        public int ID { get; set; }
        public string BudgetCode { get; set; }
        public string CostElement { get; set; }
        public string BU_ASorPS { get; set; }
        public string Quarter { get; set; }
        public Nullable<decimal> OrderPlan_Amt { get; set; }
        public Nullable<int> VKM_Year { get; set; }
    }
}
