//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cable_Pr
    {
        public string System_name { get; set; }
        public string Date { get; set; }
        public string Kernel_Loadbox_Card_ECC_Cable_CABLE_OrderNumber { get; set; }
        public string Kernel_Loadbox_Card_ECC_Cable_CABLE_SerialNumber { get; set; }
        public string Kernel_Loadbox_Card_ECC_Cable_CABLE_DeviceFunction { get; set; }
        public string Kernel_Loadbox_Card_ECC_Cable_CABLE_DeviceRevision { get; set; }
        public string Kernel_Loadbox_Card_ECC_Cable_CABLE_OptionalDescription { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Project { get; set; }
    }
}
