//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummaryTable_v3
    {
        public string ComputerID { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> ManualTotalHours { get; set; }
        public Nullable<decimal> AutomatedTotalHours { get; set; }
        public Nullable<decimal> ManualCaplTotalHours { get; set; }
        public Nullable<decimal> AutomatedCaplTotalHours { get; set; }
    }
}
