//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIO1_Card_Pr
    {
        public string System_name { get; set; }
        public string Date { get; set; }
        public string Kernel_Loadbox_Card_GIO1_CARD_BoardType { get; set; }
        public string Kernel_Loadbox_Card_GIO1_CARD_Description { get; set; }
        public string Kernel_Loadbox_Card_GIO1_CARD_BoardRevision { get; set; }
        public string Kernel_Loadbox_Card_GIO1_CARD_VER_TAG_ARRAY { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Serial_No { get; set; }
        public string Kernel_Loadbox_Card_GIO1_RepairCounter { get; set; }
        public string Kernel_Loadbox_Card_GIO1_PowerOnTime { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Firmware_Card_Major { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Firmware_Card_Minor { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Firmware_FPGA_Major { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Firmware_FPGA_Minor { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Calibration_Day { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Calibration_Month { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Calibration_Year { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Next_Calibration_Day { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Next_Calibration_Month { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Next_Calibration_Year { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Day_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Month_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_GIO1_Year_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_GIO1_BuildVersion { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Project { get; set; }
    }
}
