//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromasterImport_HW_CoGrpsEntities : DbContext
    {
        public PromasterImport_HW_CoGrpsEntities()
            : base("name=PromasterImport_HW_CoGrpsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APB_Pr> APB_Pr { get; set; }
        public virtual DbSet<BreakOutBox_1_Pr> BreakOutBox_1_Pr { get; set; }
        public virtual DbSet<BreakOutBox_Pr> BreakOutBox_Pr { get; set; }
        public virtual DbSet<Cable_1_Pr> Cable_1_Pr { get; set; }
        public virtual DbSet<Cable_Pr> Cable_Pr { get; set; }
        public virtual DbSet<EB_Cards_Pr> EB_Cards_Pr { get; set; }
        public virtual DbSet<ECC_Card_Pr> ECC_Card_Pr { get; set; }
        public virtual DbSet<ES4441_1_Pr> ES4441_1_Pr { get; set; }
        public virtual DbSet<ES4441_2_Pr> ES4441_2_Pr { get; set; }
        public virtual DbSet<GIO1_Card_Pr> GIO1_Card_Pr { get; set; }
        public virtual DbSet<GIO2_Card_Pr> GIO2_Card_Pr { get; set; }
        public virtual DbSet<Harnesadapter_1_Pr> Harnesadapter_1_Pr { get; set; }
        public virtual DbSet<Harnesadapter_Pr> Harnesadapter_Pr { get; set; }
        public virtual DbSet<IB_Card_Pr> IB_Card_Pr { get; set; }
        public virtual DbSet<IXXAT_Config_Pr> IXXAT_Config_Pr { get; set; }
        public virtual DbSet<LDU_Card_Pr> LDU_Card_Pr { get; set; }
        public virtual DbSet<OTSO_Pr> OTSO_Pr { get; set; }
        public virtual DbSet<Power_Supply_Pr> Power_Supply_Pr { get; set; }
        public virtual DbSet<PSC_Card_Pr> PSC_Card_Pr { get; set; }
        public virtual DbSet<VSC_Card_Pr> VSC_Card_Pr { get; set; }
        public virtual DbSet<WSS_Card_Pr> WSS_Card_Pr { get; set; }
        public virtual DbSet<WSS2_Card_Pr> WSS2_Card_Pr { get; set; }
        public virtual DbSet<ES4441_Pr> ES4441_Pr { get; set; }
    }
}
