//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HWInventory_Table
    {
        public int ID { get; set; }
        public string BU { get; set; }
        public string OEM { get; set; }
        public string GROUP { get; set; }
        public string ItemName_Planner { get; set; }
        public string Item_Name { get; set; }
        public string UOM { get; set; }
        public string Inventory_Type { get; set; }
        public string Serial_Number { get; set; }
        public string Bond_Number { get; set; }
        public Nullable<System.DateTime> Bond_Date { get; set; }
        public string Asset_Number { get; set; }
        public string HW_Responsible { get; set; }
        public string Handover_To { get; set; }
        public string Mode { get; set; }
        public string Remarks { get; set; }
        public string ALM_Number { get; set; }
        public string POQty { get; set; }
        public string Available_Qty { get; set; }
        public Nullable<System.DateTime> Actual_Delivery_Date { get; set; }
        public Nullable<int> PODetails_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
