//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table_orderview_test
    {
        public int RequestID { get; set; }
        public string DEPT { get; set; }
        public Nullable<bool> ApprovedSH { get; set; }
        public Nullable<int> ApprQuantity { get; set; }
        public Nullable<System.DateTime> SHAppDate { get; set; }
        public string OrderID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<bool> Ordered { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> RequestOrderDate { get; set; }
        public Nullable<bool> RequestToOrder { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> TentativeDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public string Fund { get; set; }
        public Nullable<int> OrderedQuantity { get; set; }
        public Nullable<int> DeliveredQuantity { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Dept { get; set; }
        public string BM_Number { get; set; }
        public string Task_ID { get; set; }
        public string Resource_Group_Id { get; set; }
        public string PIF_ID { get; set; }
        public Nullable<int> isCancelled { get; set; }
        public int SNo { get; set; }
        public Nullable<int> RFOQuantity { get; set; }
        public Nullable<int> OrderTable_ID { get; set; }
        public Nullable<decimal> RFOCost { get; set; }
    }
}
