//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSS_LabAdmin
    {
        public int SNo { get; set; }
        public Nullable<int> Lab_ID { get; set; }
        public string Lab_Name { get; set; }
        public string Lab { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public string Comp_DisplayName { get; set; }
        public string FQDN { get; set; }
        public string Location { get; set; }
        public string Project_Change { get; set; }
        public string Current_Project { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Responsible { get; set; }
        public string Setup_Type { get; set; }
        public Nullable<System.DateTime> From_Time { get; set; }
        public Nullable<System.DateTime> To_Time { get; set; }
    }
}
