//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromasterImport_ProjectDescEntities : DbContext
    {
        public PromasterImport_ProjectDescEntities()
            : base("name=PromasterImport_ProjectDescEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectDescription_Pr_1> ProjectDescription_Pr_1 { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
    }
}
