//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDescription_Pr_1
    {
        public string System_name { get; set; }
        public string Component_name { get; set; }
        public string Version { get; set; }
        public string Db_Version { get; set; }
        public string Date { get; set; }
        public string Details { get; set; }
        public string ToolVersion { get; set; }
        public string EMUCable { get; set; }
        public string AECUCable { get; set; }
        public string Product { get; set; }
        public string MetaEditor_Ver { get; set; }
        public string ProjectBuilder_Ver { get; set; }
        public string Ascet_Ver { get; set; }
        public string ProjectEditor_Ver { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
