//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestItems_Table_bkp
    {
        public int RequestID { get; set; }
        public string BU { get; set; }
        public string DEPT { get; set; }
        public string Group { get; set; }
        public string OEM { get; set; }
        public string ItemName { get; set; }
        public string Category { get; set; }
        public string CostElement { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ReqQuantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Comments { get; set; }
        public string RequestorNT { get; set; }
        public Nullable<bool> ApprovalDH { get; set; }
        public Nullable<int> ApprQuantity { get; set; }
        public Nullable<decimal> ApprCost { get; set; }
        public Nullable<bool> ApprovedDH { get; set; }
        public string DHNT { get; set; }
        public Nullable<bool> ApprovalSH { get; set; }
        public Nullable<bool> ApprovedSH { get; set; }
        public string SHNT { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> DHAppDate { get; set; }
        public Nullable<System.DateTime> SHAppDate { get; set; }
        public string OrderID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<bool> Ordered { get; set; }
    }
}
