//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeConfig
    {
        public int SNo { get; set; }
        public string Night_From_Time { get; set; }
        public string Night_To_Time { get; set; }
        public string Weekend_From_Time { get; set; }
        public string Weekend_To_Time { get; set; }
        public System.DateTime Date_Modified { get; set; }
    }
}
