//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKMPlanning_GRMEMSupport
    {
        public int SNo { get; set; }
        public string NTID { get; set; }
        public string Employee_Number { get; set; }
        public string Employee_Name { get; set; }
        public int Product_Area_ID { get; set; }
        public int Section_ID { get; set; }
        public int Department_ID { get; set; }
        public int Group_ID { get; set; }
        public string Level { get; set; }
        public int SAP_Role { get; set; }
        public string VKM_Role { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Plan_Sum { get; set; }
        public Nullable<decimal> Jan { get; set; }
        public Nullable<decimal> Feb { get; set; }
        public Nullable<decimal> Mar { get; set; }
        public Nullable<decimal> Apr { get; set; }
        public Nullable<decimal> May { get; set; }
        public Nullable<decimal> Jun { get; set; }
        public Nullable<decimal> Jul { get; set; }
        public Nullable<decimal> Aug { get; set; }
        public Nullable<decimal> Sep { get; set; }
        public Nullable<decimal> Oct { get; set; }
        public Nullable<decimal> Nov { get; set; }
        public Nullable<decimal> Dec { get; set; }
        public Nullable<decimal> PYO { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
