//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetingToolTestDBEntities : DbContext
    {
        public BudgetingToolTestDBEntities()
            : base("name=BudgetingToolTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OEMList> OEMLists { get; set; }
        public virtual DbSet<SPOTONData> SPOTONDatas { get; set; }
        public virtual DbSet<tbl_categoryList> tbl_categoryList { get; set; }
        public virtual DbSet<tbl_depts> tbl_depts { get; set; }
        public virtual DbSet<tbl_ItemsCostList> tbl_ItemsCostList { get; set; }
        public virtual DbSet<tbl_RequestItemsRepo> tbl_RequestItemsRepo { get; set; }
    }
}
