//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetingToolDB_Entities : DbContext
    {
        public BudgetingToolDB_Entities()
            : base("name=BudgetingToolDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BU_SPOCS> BU_SPOCS { get; set; }
        public virtual DbSet<BU_Table> BU_Table { get; set; }
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<CmmtItem_Table> CmmtItem_Table { get; set; }
        public virtual DbSet<Cockpit_UserIDs_Table> Cockpit_UserIDs_Table { get; set; }
        public virtual DbSet<CostElement_Table> CostElement_Table { get; set; }
        public virtual DbSet<Currency_Conversion_Table> Currency_Conversion_Table { get; set; }
        public virtual DbSet<Currency_Table> Currency_Table { get; set; }
        public virtual DbSet<DEPT_Table> DEPT_Table { get; set; }
        public virtual DbSet<Fund_Table> Fund_Table { get; set; }
        public virtual DbSet<Groups_Table> Groups_Table { get; set; }
        public virtual DbSet<Groups_Table_Aug> Groups_Table_Aug { get; set; }
        public virtual DbSet<Groups_Table_New> Groups_Table_New { get; set; }
        public virtual DbSet<Groups_Table_Test> Groups_Table_Test { get; set; }
        public virtual DbSet<HC_Budget_Table> HC_Budget_Table { get; set; }
        public virtual DbSet<HC_Role_Table> HC_Role_Table { get; set; }
        public virtual DbSet<HC_Table> HC_Table { get; set; }
        public virtual DbSet<HwDamageCost_Location_Table> HwDamageCost_Location_Table { get; set; }
        public virtual DbSet<HwDamageCost_Month_Table> HwDamageCost_Month_Table { get; set; }
        public virtual DbSet<HWDamageCost_OEM_Table> HWDamageCost_OEM_Table { get; set; }
        public virtual DbSet<HwDamageCost_Table> HwDamageCost_Table { get; set; }
        public virtual DbSet<HwDamageCost_UserIDs_Table> HwDamageCost_UserIDs_Table { get; set; }
        public virtual DbSet<LeadTime_Table> LeadTime_Table { get; set; }
        public virtual DbSet<OEM_Table> OEM_Table { get; set; }
        public virtual DbSet<Order_Status_Table> Order_Status_Table { get; set; }
        public virtual DbSet<PlanningRequestor_Table> PlanningRequestor_Table { get; set; }
        public virtual DbSet<SPOTONData_Table_2022> SPOTONData_Table_2022 { get; set; }
        public virtual DbSet<tbl_UserIDs_Table> tbl_UserIDs_Table { get; set; }
        public virtual DbSet<TravelCost_Table> TravelCost_Table { get; set; }
        public virtual DbSet<BGSW_BudgetCenter_Table> BGSW_BudgetCenter_Table { get; set; }
        public virtual DbSet<BGSW_BudgetCenterIDvsSection_Table> BGSW_BudgetCenterIDvsSection_Table { get; set; }
        public virtual DbSet<BGSW_BudgetCode_Table> BGSW_BudgetCode_Table { get; set; }
        public virtual DbSet<BGSW_F05F06_PurchaseType_Table> BGSW_F05F06_PurchaseType_Table { get; set; }
        public virtual DbSet<BGSW_ItemOrderType_Table> BGSW_ItemOrderType_Table { get; set; }
        public virtual DbSet<BGSW_MaterialGroup_Table> BGSW_MaterialGroup_Table { get; set; }
        public virtual DbSet<BGSW_UnloadingPoint_Table> BGSW_UnloadingPoint_Table { get; set; }
        public virtual DbSet<BGSW_UOM_Table> BGSW_UOM_Table { get; set; }
        public virtual DbSet<BGSW_VKMSPOCs> BGSW_VKMSPOCs { get; set; }
        public virtual DbSet<HC_SkillSet_Table> HC_SkillSet_Table { get; set; }
        public virtual DbSet<PODetails_Table> PODetails_Table { get; set; }
        public virtual DbSet<POSPOC_Team> POSPOC_Team { get; set; }
        public virtual DbSet<SR_Responsible_Buyer_table> SR_Responsible_Buyer_table { get; set; }
        public virtual DbSet<SR_Responsible_Manager_table> SR_Responsible_Manager_table { get; set; }
        public virtual DbSet<Utilization_Table2021> Utilization_Table2021 { get; set; }
        public virtual DbSet<RequestItems_Table> RequestItems_Table { get; set; }
        public virtual DbSet<OrderStatusDescription> OrderStatusDescriptions { get; set; }
        public virtual DbSet<ItemsCostList_Table> ItemsCostList_Table { get; set; }
        public virtual DbSet<OrderingRequestor_Table> OrderingRequestor_Table { get; set; }
        public virtual DbSet<Planning_EM_Table> Planning_EM_Table { get; set; }
        public virtual DbSet<Planning_HOE_Table> Planning_HOE_Table { get; set; }
    }
}
