//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPC_Summary_Table
    {
        public int ID { get; set; }
        public Nullable<int> LabTypeID { get; set; }
        public string LabTypeName { get; set; }
        public string LabTypeDesc { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string SiteName { get; set; }
        public string RBCode { get; set; }
        public Nullable<int> LabID { get; set; }
        public string LabName { get; set; }
        public string LabDesc { get; set; }
        public Nullable<int> ComputerID { get; set; }
        public string Comp_DisplayName { get; set; }
        public string FQDN { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Action { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
