//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware_Desc_Pr
    {
        public string System_name { get; set; }
        public string Date { get; set; }
        public string EEPName { get; set; }
        public string EEPBuildDate { get; set; }
        public string EEPDatabaseVersion { get; set; }
        public string PCHostName { get; set; }
        public string RTPCSoftwareVersion { get; set; }
        public string RTPCName { get; set; }
        public string ToolChainVersion { get; set; }
        public string RBCCAFVersion { get; set; }
        public string LabCarType { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
