//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_Table
    {
        public int ID { get; set; }
        public string SkillSet { get; set; }
        public string Role { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Plan { get; set; }
        public Nullable<decimal> Utilize { get; set; }
    }
}
