//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabComputersPr
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> TrackerConfigId { get; set; }
        public Nullable<int> LabId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string FQDN { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
