//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning_EM_table_bkp
    {
        public int ID { get; set; }
        public string NTID { get; set; }
        public string FullName { get; set; }
        public string Department { get; set; }
        public string Group { get; set; }
        public string Proxy_NTID { get; set; }
        public string Proxy_FullName { get; set; }
        public string Updated_By { get; set; }
        public Nullable<bool> Enable_Proxy { get; set; }
    }
}
