//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODet_Temp
    {
        public int ID { get; set; }
        public string RequestID { get; set; }
        public string BU { get; set; }
        public string BudgetCode { get; set; }
        public string SCNO { get; set; }
        public string PONO { get; set; }
        public Nullable<System.DateTime> Orddt { get; set; }
        public Nullable<System.DateTime> POReleaseDt { get; set; }
        public Nullable<System.DateTime> ReqDt { get; set; }
        public Nullable<System.DateTime> TentativeDelDt { get; set; }
        public Nullable<System.DateTime> ActualDelDt { get; set; }
        public string PORaisedBY { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public string OrderStatus { get; set; }
        public string Fund { get; set; }
    }
}
