//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUsersdbTSUA
    {
        public int Id { get; set; }
        public string USER_NTID { get; set; }
        public string USER_OEM { get; set; }
        public string USER_NAME { get; set; }
        public string PROJECT { get; set; }
        public string PROJECT_RESPONSIBLE { get; set; }
        public string LOCATION { get; set; }
    }
}
