//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tactivitiesUpdate
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int SessionId { get; set; }
        public int ComputerId { get; set; }
        public int IsActive { get; set; }
        public int Expired { get; set; }
        public int StartDate { get; set; }
        public int EndDate { get; set; }
        public string Info { get; set; }
    }
}
