//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC_Reports_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSS_Card_Pr
    {
        public string System_name { get; set; }
        public string Date { get; set; }
        public string Kernel_Loadbox_Card_WSS_CARD_BoardType { get; set; }
        public string Kernel_Loadbox_Card_WSS_CARD_Description { get; set; }
        public string Kernel_Loadbox_Card_WSS_CARD_BoardRevision { get; set; }
        public string Kernel_Loadbox_Card_WSS_CARD_VER_TAG_ARRAY { get; set; }
        public string Kernel_Loadbox_Card_WSS_Serial_No { get; set; }
        public string Kernel_Loadbox_Card_WSS_RepairCounter { get; set; }
        public string Kernel_Loadbox_Card_WSS_PowerOnTime { get; set; }
        public string Kernel_Loadbox_Card_WSS_Firmware_Card_Major { get; set; }
        public string Kernel_Loadbox_Card_WSS_Firmware_Card_Minor { get; set; }
        public string Kernel_Loadbox_Card_WSS_Firmware_FPGA_Major { get; set; }
        public string Kernel_Loadbox_Card_WSS_Firmware_FPGA_Minor { get; set; }
        public string Kernel_Loadbox_Card_WSS_Calibration_Day { get; set; }
        public string Kernel_Loadbox_Card_WSS_Calibration_Month { get; set; }
        public string Kernel_Loadbox_Card_WSS_Calibration_Year { get; set; }
        public string Kernel_Loadbox_Card_WSS_Next_Calibration_Day { get; set; }
        public string Kernel_Loadbox_Card_WSS_Next_Calibration_Month { get; set; }
        public string Kernel_Loadbox_Card_WSS_Next_Calibration_Year { get; set; }
        public string Kernel_Loadbox_Card_WSS_Day_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_WSS_Month_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_WSS_Year_of_Creation { get; set; }
        public string Kernel_Loadbox_Card_WSS_BuildVersion { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Project { get; set; }
    }
}
